/*
 * Copyright (c) 2022 Teslabs Engineering S.L.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ARTERYF43X_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ARTERYF43X_CLOCKS_H_

#include "atery-clocks-common.h"

/**
 * @name Register offsets
 * @{
 */

#define ARTERY_AHB1EN_OFFSET 0x30U
#define ARTERY_AHB2EN_OFFSET 0x34U
#define ARTERY_AHB3EN_OFFSET 0x38U
#define ARTERY_APB1EN_OFFSET 0x40U
#define ARTERY_APB2EN_OFFSET 0x44U

/** @} */

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */

/* AHB1 peripherals */
#define ARTERY_CLOCK_GPIOA  ARTERY_CLOCK_CONFIG(AHB1EN, 0U)
#define ARTERY_CLOCK_GPIOB  ARTERY_CLOCK_CONFIG(AHB1EN, 1U)
#define ARTERY_CLOCK_GPIOC  ARTERY_CLOCK_CONFIG(AHB1EN, 2U)
#define ARTERY_CLOCK_GPIOD  ARTERY_CLOCK_CONFIG(AHB1EN, 3U)
#define ARTERY_CLOCK_GPIOE  ARTERY_CLOCK_CONFIG(AHB1EN, 4U)
#define ARTERY_CLOCK_GPIOF  ARTERY_CLOCK_CONFIG(AHB1EN, 5U)
#define ARTERY_CLOCK_GPIOG  ARTERY_CLOCK_CONFIG(AHB1EN, 6U)
#define ARTERY_CLOCK_GPIOH  ARTERY_CLOCK_CONFIG(AHB1EN, 7U)
#define ARTERY_CLOCK_CRC    ARTERY_CLOCK_CONFIG(AHB1EN, 12U)
#define ARTERY_CLOCK_EDMA   ARTERY_CLOCK_CONFIG(AHB1EN, 21U)
#define ARTERY_CLOCK_DMA1   ARTERY_CLOCK_CONFIG(AHB1EN, 22U)
#define ARTERY_CLOCK_DMA2   ARTERY_CLOCK_CONFIG(AHB1EN, 24U)
#define ARTERY_CLOCK_EMAC   ARTERY_CLOCK_CONFIG(AHB1EN, 25U)
#define ARTERY_CLOCK_EMACTX ARTERY_CLOCK_CONFIG(AHB1EN, 26U)
#define ARTERY_CLOCK_EMACRX ARTERY_CLOCK_CONFIG(AHB1EN, 27U)
#define ARTERY_CLOCK_EMACTP ARTERY_CLOCK_CONFIG(AHB1EN, 28U)
#define ARTERY_CLOCK_OTGFS2 ARTERY_CLOCK_CONFIG(AHB1EN, 29U)

/* AHB2 peripherals */
#define ARTERY_CLOCK_DVP    ARTERY_CLOCK_CONFIG(AHB2EN, 0U)
#define ARTERY_CLOCK_OTGFS1 ARTERY_CLOCK_CONFIG(AHB2EN, 7U)
#define ARTERY_CLOCK_SDIO1  ARTERY_CLOCK_CONFIG(AHB2EN, 15U)

/* AHB3 peripherals */
#define ARTERY_CLOCK_XMC   ARTERY_CLOCK_CONFIG(AHB3EN, 0U)
#define ARTERY_CLOCK_QSPI1 ARTERY_CLOCK_CONFIG(AHB3EN, 1U)
#define ARTERY_CLOCK_QSPI2 ARTERY_CLOCK_CONFIG(AHB3EN, 14U)
#define ARTERY_CLOCK_SDIO2 ARTERY_CLOCK_CONFIG(AHB3EN, 15U)

/* APB1 peripherals */
#define ARTERY_CLOCK_TMR2   ARTERY_CLOCK_CONFIG(APB1EN, 0U)
#define ARTERY_CLOCK_TMR3   ARTERY_CLOCK_CONFIG(APB1EN, 1U)
#define ARTERY_CLOCK_TMR4   ARTERY_CLOCK_CONFIG(APB1EN, 2U)
#define ARTERY_CLOCK_TMR5   ARTERY_CLOCK_CONFIG(APB1EN, 3U)
#define ARTERY_CLOCK_TMR6   ARTERY_CLOCK_CONFIG(APB1EN, 4U)
#define ARTERY_CLOCK_TMR7   ARTERY_CLOCK_CONFIG(APB1EN, 5U)
#define ARTERY_CLOCK_TMR12  ARTERY_CLOCK_CONFIG(APB1EN, 6U)
#define ARTERY_CLOCK_TMR13  ARTERY_CLOCK_CONFIG(APB1EN, 7U)
#define ARTERY_CLOCK_TMR14  ARTERY_CLOCK_CONFIG(APB1EN, 8U)
#define ARTERY_CLOCK_WWDT   ARTERY_CLOCK_CONFIG(APB1EN, 11U)
#define ARTERY_CLOCK_SPI2   ARTERY_CLOCK_CONFIG(APB1EN, 14U)
#define ARTERY_CLOCK_SPI3   ARTERY_CLOCK_CONFIG(APB1EN, 15U)
#define ARTERY_CLOCK_USART2 ARTERY_CLOCK_CONFIG(APB1EN, 17U)
#define ARTERY_CLOCK_USART3 ARTERY_CLOCK_CONFIG(APB1EN, 18U)
#define ARTERY_CLOCK_UART4  ARTERY_CLOCK_CONFIG(APB1EN, 19U)
#define ARTERY_CLOCK_UART5  ARTERY_CLOCK_CONFIG(APB1EN, 20U)
#define ARTERY_CLOCK_I2C1   ARTERY_CLOCK_CONFIG(APB1EN, 21U)
#define ARTERY_CLOCK_I2C2   ARTERY_CLOCK_CONFIG(APB1EN, 22U)
#define ARTERY_CLOCK_I2C3   ARTERY_CLOCK_CONFIG(APB1EN, 23U)
#define ARTERY_CLOCK_CAN1   ARTERY_CLOCK_CONFIG(APB1EN, 25U)
#define ARTERY_CLOCK_CAN2   ARTERY_CLOCK_CONFIG(APB1EN, 26U)
#define ARTERY_CLOCK_PWC    ARTERY_CLOCK_CONFIG(APB1EN, 28U)
#define ARTERY_CLOCK_DAC    ARTERY_CLOCK_CONFIG(APB1EN, 29U)
#define ARTERY_CLOCK_UART7  ARTERY_CLOCK_CONFIG(APB1EN, 30U)
#define ARTERY_CLOCK_UART8  ARTERY_CLOCK_CONFIG(APB1EN, 31U)

/* APB2 peripherals */
#define ARTERY_CLOCK_TMR1   ARTERY_CLOCK_CONFIG(APB2EN, 0U)
#define ARTERY_CLOCK_TMR8   ARTERY_CLOCK_CONFIG(APB2EN, 1U)
#define ARTERY_CLOCK_USART1 ARTERY_CLOCK_CONFIG(APB2EN, 4U)
#define ARTERY_CLOCK_USART6 ARTERY_CLOCK_CONFIG(APB2EN, 5U)
#define ARTERY_CLOCK_ADC1   ARTERY_CLOCK_CONFIG(APB2EN, 8U)
#define ARTERY_CLOCK_ADC2   ARTERY_CLOCK_CONFIG(APB2EN, 9U)
#define ARTERY_CLOCK_ADC3   ARTERY_CLOCK_CONFIG(APB2EN, 10U)
#define ARTERY_CLOCK_SPI1   ARTERY_CLOCK_CONFIG(APB1EN, 12U)
#define ARTERY_CLOCK_SPI4   ARTERY_CLOCK_CONFIG(APB1EN, 13U)
#define ARTERY_CLOCK_SCFG   ARTERY_CLOCK_CONFIG(APB1EN, 14U)
#define ARTERY_CLOCK_TMR9   ARTERY_CLOCK_CONFIG(APB2EN, 16U)
#define ARTERY_CLOCK_TMR10  ARTERY_CLOCK_CONFIG(APB2EN, 17U)
#define ARTERY_CLOCK_TMR11  ARTERY_CLOCK_CONFIG(APB2EN, 18U)
#define ARTERY_CLOCK_TMR20  ARTERY_CLOCK_CONFIG(APB2EN, 20U)
#define ARTERY_CLOCK_ACC    ARTERY_CLOCK_CONFIG(APB2EN, 29U)

/** @} */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ARTERYF43X_CLOCKS_H_ */
